// Copyright (c) 2005-2023 Code Synthesis.
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis gives permission
// to link this program with the Xerces-C++ library (or with modified
// versions of Xerces-C++ that use the same license as Xerces-C++), and
// distribute linked combinations including the two. You must obey the GNU
// General Public License version 2 in all respects for all of the code
// used other than Xerces-C++. If you modify this copy of the program, you
// may extend this exception to your version of the program, but you are
// not obligated to do so. If you do not wish to do so, delete this
// exception statement from your version.
//
// Furthermore, Code Synthesis makes a special exception for the Free/Libre
// and Open Source Software (FLOSS) which is described in the accompanying
// FLOSSE file.
//

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/pre.hxx>

#include "batterychargecondition.hxx"

#include "IDREF.hxx"

namespace streit
{
  // batterychargecondition
  //

  const batterychargecondition::deviceref_type& batterychargecondition::
  deviceref () const
  {
    return this->deviceref_.get ();
  }

  batterychargecondition::deviceref_type& batterychargecondition::
  deviceref ()
  {
    return this->deviceref_.get ();
  }

  void batterychargecondition::
  deviceref (const deviceref_type& x)
  {
    this->deviceref_.set (x);
  }

  void batterychargecondition::
  deviceref (::std::unique_ptr< deviceref_type > x)
  {
    this->deviceref_.set (std::move (x));
  }

  const batterychargecondition::tankref_optional& batterychargecondition::
  tankref () const
  {
    return this->tankref_;
  }

  batterychargecondition::tankref_optional& batterychargecondition::
  tankref ()
  {
    return this->tankref_;
  }

  void batterychargecondition::
  tankref (const tankref_type& x)
  {
    this->tankref_.set (x);
  }

  void batterychargecondition::
  tankref (const tankref_optional& x)
  {
    this->tankref_ = x;
  }

  void batterychargecondition::
  tankref (::std::unique_ptr< tankref_type > x)
  {
    this->tankref_.set (std::move (x));
  }
}

#include <xsd/cxx/xml/dom/parsing-source.hxx>

namespace streit
{
  // batterychargecondition
  //

  batterychargecondition::
  batterychargecondition (const ::xml_schema::float_& _xsd_float__base,
                          const deviceref_type& deviceref)
  : ::xsd::cxx::tree::fundamental_base< ::xml_schema::float_, char, ::xml_schema::simple_type > (_xsd_float__base),
    deviceref_ (deviceref, this),
    tankref_ (this)
  {
  }

  batterychargecondition::
  batterychargecondition (const batterychargecondition& x,
                          ::xml_schema::flags f,
                          ::xml_schema::container* c)
  : ::xsd::cxx::tree::fundamental_base< ::xml_schema::float_, char, ::xml_schema::simple_type > (x, f, c),
    deviceref_ (x.deviceref_, f, this),
    tankref_ (x.tankref_, f, this)
  {
  }

  batterychargecondition::
  batterychargecondition (const ::xercesc::DOMElement& e,
                          ::xml_schema::flags f,
                          ::xml_schema::container* c)
  : ::xsd::cxx::tree::fundamental_base< ::xml_schema::float_, char, ::xml_schema::simple_type > (e, f | ::xml_schema::flags::base, c),
    deviceref_ (this),
    tankref_ (this)
  {
    if ((f & ::xml_schema::flags::base) == 0)
    {
      ::xsd::cxx::xml::dom::parser< char > p (e, false, false, true);
      this->parse (p, f);
    }
  }

  void batterychargecondition::
  parse (::xsd::cxx::xml::dom::parser< char >& p,
         ::xml_schema::flags f)
  {
    while (p.more_attributes ())
    {
      const ::xercesc::DOMAttr& i (p.next_attribute ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      if (n.name () == "deviceref" && n.namespace_ ().empty ())
      {
        this->deviceref_.set (deviceref_traits::create (i, f, this));
        continue;
      }

      if (n.name () == "tankref" && n.namespace_ ().empty ())
      {
        this->tankref_.set (tankref_traits::create (i, f, this));
        continue;
      }
    }

    if (!deviceref_.present ())
    {
      throw ::xsd::cxx::tree::expected_attribute< char > (
        "deviceref",
        "");
    }
  }

  batterychargecondition* batterychargecondition::
  _clone (::xml_schema::flags f,
          ::xml_schema::container* c) const
  {
    return new class batterychargecondition (*this, f, c);
  }

  batterychargecondition& batterychargecondition::
  operator= (const batterychargecondition& x)
  {
    if (this != &x)
    {
      static_cast< ::xsd::cxx::tree::fundamental_base< ::xml_schema::float_, char, ::xml_schema::simple_type >& > (*this) = x;
      this->deviceref_ = x.deviceref_;
      this->tankref_ = x.tankref_;
    }

    return *this;
  }

  batterychargecondition::
  ~batterychargecondition ()
  {
  }
}

#include <ostream>

namespace streit
{
  ::std::ostream&
  operator<< (::std::ostream& o, const batterychargecondition& i)
  {
    o << static_cast< const ::xsd::cxx::tree::fundamental_base< ::xml_schema::float_, char, ::xml_schema::simple_type >& > (i);

    o << ::std::endl << "deviceref: " << i.deviceref ();
    if (i.tankref ())
    {
      o << ::std::endl << "tankref: " << *i.tankref ();
    }

    return o;
  }
}

#include <istream>
#include <xsd/cxx/xml/sax/std-input-source.hxx>
#include <xsd/cxx/tree/error-handler.hxx>

namespace streit
{
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

