// Copyright (c) 2005-2023 Code Synthesis.
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis gives permission
// to link this program with the Xerces-C++ library (or with modified
// versions of Xerces-C++ that use the same license as Xerces-C++), and
// distribute linked combinations including the two. You must obey the GNU
// General Public License version 2 in all respects for all of the code
// used other than Xerces-C++. If you modify this copy of the program, you
// may extend this exception to your version of the program, but you are
// not obligated to do so. If you do not wish to do so, delete this
// exception statement from your version.
//
// Furthermore, Code Synthesis makes a special exception for the Free/Libre
// and Open Source Software (FLOSS) which is described in the accompanying
// FLOSSE file.
//

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/pre.hxx>

#include "buddy.hxx"

#include "ID.hxx"

#include "personalType.hxx"

#include "addressType.hxx"

#include "contactType.hxx"

#include "equipmentType.hxx"

#include "medical.hxx"

#include "education.hxx"

#include "divepermissions.hxx"

#include "diveinsurances.hxx"

#include "notesType.hxx"

namespace streit
{
  // buddy
  //

  const buddy::student_optional& buddy::
  student () const
  {
    return this->student_;
  }

  buddy::student_optional& buddy::
  student ()
  {
    return this->student_;
  }

  void buddy::
  student (const student_type& x)
  {
    this->student_.set (x);
  }

  void buddy::
  student (const student_optional& x)
  {
    this->student_ = x;
  }

  void buddy::
  student (::std::unique_ptr< student_type > x)
  {
    this->student_.set (std::move (x));
  }
}

#include <xsd/cxx/xml/dom/parsing-source.hxx>

namespace streit
{
  // buddy
  //

  buddy::
  buddy (const id_type& id,
         const personal_type& personal)
  : ::streit::personType (id,
                          personal),
    student_ (this)
  {
  }

  buddy::
  buddy (const id_type& id,
         ::std::unique_ptr< personal_type > personal)
  : ::streit::personType (id,
                          std::move (personal)),
    student_ (this)
  {
  }

  buddy::
  buddy (const buddy& x,
         ::xml_schema::flags f,
         ::xml_schema::container* c)
  : ::streit::personType (x, f, c),
    student_ (x.student_, f, this)
  {
  }

  buddy::
  buddy (const ::xercesc::DOMElement& e,
         ::xml_schema::flags f,
         ::xml_schema::container* c)
  : ::streit::personType (e, f | ::xml_schema::flags::base, c),
    student_ (this)
  {
    if ((f & ::xml_schema::flags::base) == 0)
    {
      ::xsd::cxx::xml::dom::parser< char > p (e, true, false, true);
      this->parse (p, f);
    }
  }

  void buddy::
  parse (::xsd::cxx::xml::dom::parser< char >& p,
         ::xml_schema::flags f)
  {
    this->::streit::personType::parse (p, f);

    for (; p.more_content (); p.next_content (false))
    {
      const ::xercesc::DOMElement& i (p.cur_element ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      // student
      //
      if (n.name () == "student" && n.namespace_ () == "http://www.streit.cc/uddf/3.2/")
      {
        ::std::unique_ptr< student_type > r (
          student_traits::create (i, f, this));

        if (!this->student_)
        {
          this->student_.set (::std::move (r));
          continue;
        }
      }

      break;
    }
  }

  buddy* buddy::
  _clone (::xml_schema::flags f,
          ::xml_schema::container* c) const
  {
    return new class buddy (*this, f, c);
  }

  buddy& buddy::
  operator= (const buddy& x)
  {
    if (this != &x)
    {
      static_cast< ::streit::personType& > (*this) = x;
      this->student_ = x.student_;
    }

    return *this;
  }

  buddy::
  ~buddy ()
  {
  }
}

#include <ostream>

namespace streit
{
  ::std::ostream&
  operator<< (::std::ostream& o, const buddy& i)
  {
    o << static_cast< const ::streit::personType& > (i);

    if (i.student ())
    {
      o << ::std::endl << "student: " << *i.student ();
    }

    return o;
  }
}

#include <istream>
#include <xsd/cxx/xml/sax/std-input-source.hxx>
#include <xsd/cxx/tree/error-handler.hxx>

namespace streit
{
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

