// Copyright (c) 2005-2023 Code Synthesis.
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis gives permission
// to link this program with the Xerces-C++ library (or with modified
// versions of Xerces-C++ that use the same license as Xerces-C++), and
// distribute linked combinations including the two. You must obey the GNU
// General Public License version 2 in all respects for all of the code
// used other than Xerces-C++. If you modify this copy of the program, you
// may extend this exception to your version of the program, but you are
// not obligated to do so. If you do not wish to do so, delete this
// exception statement from your version.
//
// Furthermore, Code Synthesis makes a special exception for the Free/Libre
// and Open Source Software (FLOSS) which is described in the accompanying
// FLOSSE file.
//

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/pre.hxx>

#include "buehlmannType.hxx"

#include "ID.hxx"

#include "tissueType.hxx"

namespace streit
{
  // buehlmannType
  //

  const buehlmannType::tissue_sequence& buehlmannType::
  tissue () const
  {
    return this->tissue_;
  }

  buehlmannType::tissue_sequence& buehlmannType::
  tissue ()
  {
    return this->tissue_;
  }

  void buehlmannType::
  tissue (const tissue_sequence& s)
  {
    this->tissue_ = s;
  }

  const buehlmannType::gradientfactorhigh_optional& buehlmannType::
  gradientfactorhigh () const
  {
    return this->gradientfactorhigh_;
  }

  buehlmannType::gradientfactorhigh_optional& buehlmannType::
  gradientfactorhigh ()
  {
    return this->gradientfactorhigh_;
  }

  void buehlmannType::
  gradientfactorhigh (const gradientfactorhigh_type& x)
  {
    this->gradientfactorhigh_.set (x);
  }

  void buehlmannType::
  gradientfactorhigh (const gradientfactorhigh_optional& x)
  {
    this->gradientfactorhigh_ = x;
  }

  const buehlmannType::gradientfactorlow_optional& buehlmannType::
  gradientfactorlow () const
  {
    return this->gradientfactorlow_;
  }

  buehlmannType::gradientfactorlow_optional& buehlmannType::
  gradientfactorlow ()
  {
    return this->gradientfactorlow_;
  }

  void buehlmannType::
  gradientfactorlow (const gradientfactorlow_type& x)
  {
    this->gradientfactorlow_.set (x);
  }

  void buehlmannType::
  gradientfactorlow (const gradientfactorlow_optional& x)
  {
    this->gradientfactorlow_ = x;
  }
}

#include <xsd/cxx/xml/dom/parsing-source.hxx>

namespace streit
{
  // buehlmannType
  //

  buehlmannType::
  buehlmannType (const id_type& id)
  : ::streit::ID_TYPE (id),
    tissue_ (this),
    gradientfactorhigh_ (this),
    gradientfactorlow_ (this)
  {
  }

  buehlmannType::
  buehlmannType (const buehlmannType& x,
                 ::xml_schema::flags f,
                 ::xml_schema::container* c)
  : ::streit::ID_TYPE (x, f, c),
    tissue_ (x.tissue_, f, this),
    gradientfactorhigh_ (x.gradientfactorhigh_, f, this),
    gradientfactorlow_ (x.gradientfactorlow_, f, this)
  {
  }

  buehlmannType::
  buehlmannType (const ::xercesc::DOMElement& e,
                 ::xml_schema::flags f,
                 ::xml_schema::container* c)
  : ::streit::ID_TYPE (e, f | ::xml_schema::flags::base, c),
    tissue_ (this),
    gradientfactorhigh_ (this),
    gradientfactorlow_ (this)
  {
    if ((f & ::xml_schema::flags::base) == 0)
    {
      ::xsd::cxx::xml::dom::parser< char > p (e, true, false, true);
      this->parse (p, f);
    }
  }

  void buehlmannType::
  parse (::xsd::cxx::xml::dom::parser< char >& p,
         ::xml_schema::flags f)
  {
    this->::streit::ID_TYPE::parse (p, f);

    for (; p.more_content (); p.next_content (false))
    {
      const ::xercesc::DOMElement& i (p.cur_element ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      // tissue
      //
      if (n.name () == "tissue" && n.namespace_ () == "http://www.streit.cc/uddf/3.2/")
      {
        ::std::unique_ptr< tissue_type > r (
          tissue_traits::create (i, f, this));

        this->tissue_.push_back (::std::move (r));
        continue;
      }

      // gradientfactorhigh
      //
      if (n.name () == "gradientfactorhigh" && n.namespace_ () == "http://www.streit.cc/uddf/3.2/")
      {
        if (!this->gradientfactorhigh_)
        {
          this->gradientfactorhigh_.set (gradientfactorhigh_traits::create (i, f, this));
          continue;
        }
      }

      // gradientfactorlow
      //
      if (n.name () == "gradientfactorlow" && n.namespace_ () == "http://www.streit.cc/uddf/3.2/")
      {
        if (!this->gradientfactorlow_)
        {
          this->gradientfactorlow_.set (gradientfactorlow_traits::create (i, f, this));
          continue;
        }
      }

      break;
    }
  }

  buehlmannType* buehlmannType::
  _clone (::xml_schema::flags f,
          ::xml_schema::container* c) const
  {
    return new class buehlmannType (*this, f, c);
  }

  buehlmannType& buehlmannType::
  operator= (const buehlmannType& x)
  {
    if (this != &x)
    {
      static_cast< ::streit::ID_TYPE& > (*this) = x;
      this->tissue_ = x.tissue_;
      this->gradientfactorhigh_ = x.gradientfactorhigh_;
      this->gradientfactorlow_ = x.gradientfactorlow_;
    }

    return *this;
  }

  buehlmannType::
  ~buehlmannType ()
  {
  }
}

#include <ostream>

namespace streit
{
  ::std::ostream&
  operator<< (::std::ostream& o, const buehlmannType& i)
  {
    o << static_cast< const ::streit::ID_TYPE& > (i);

    for (buehlmannType::tissue_const_iterator
         b (i.tissue ().begin ()), e (i.tissue ().end ());
         b != e; ++b)
    {
      o << ::std::endl << "tissue: " << *b;
    }

    if (i.gradientfactorhigh ())
    {
      o << ::std::endl << "gradientfactorhigh: " << *i.gradientfactorhigh ();
    }

    if (i.gradientfactorlow ())
    {
      o << ::std::endl << "gradientfactorlow: " << *i.gradientfactorlow ();
    }

    return o;
  }
}

#include <istream>
#include <xsd/cxx/xml/sax/std-input-source.hxx>
#include <xsd/cxx/tree/error-handler.hxx>

namespace streit
{
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

