// Copyright (c) 2005-2023 Code Synthesis.
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis gives permission
// to link this program with the Xerces-C++ library (or with modified
// versions of Xerces-C++ that use the same license as Xerces-C++), and
// distribute linked combinations including the two. You must obey the GNU
// General Public License version 2 in all respects for all of the code
// used other than Xerces-C++. If you modify this copy of the program, you
// may extend this exception to your version of the program, but you are
// not obligated to do so. If you do not wish to do so, delete this
// exception statement from your version.
//
// Furthermore, Code Synthesis makes a special exception for the Free/Libre
// and Open Source Software (FLOSS) which is described in the accompanying
// FLOSSE file.
//

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/pre.hxx>

#include "diveplan.hxx"

namespace streit
{
  // diveplan
  //

  diveplan::
  diveplan (value v)
  : ::xml_schema::string (_xsd_diveplan_literals_[v])
  {
  }

  diveplan::
  diveplan (const char* v)
  : ::xml_schema::string (v)
  {
  }

  diveplan::
  diveplan (const ::std::string& v)
  : ::xml_schema::string (v)
  {
  }

  diveplan::
  diveplan (const ::xml_schema::string& v)
  : ::xml_schema::string (v)
  {
  }

  diveplan::
  diveplan (const diveplan& v,
            ::xml_schema::flags f,
            ::xml_schema::container* c)
  : ::xml_schema::string (v, f, c)
  {
  }

  diveplan& diveplan::
  operator= (value v)
  {
    static_cast< ::xml_schema::string& > (*this) = 
    ::xml_schema::string (_xsd_diveplan_literals_[v]);

    return *this;
  }
}

#include <xsd/cxx/xml/dom/parsing-source.hxx>

namespace streit
{
  // diveplan
  //

  diveplan::
  diveplan (const ::xercesc::DOMElement& e,
            ::xml_schema::flags f,
            ::xml_schema::container* c)
  : ::xml_schema::string (e, f, c)
  {
    _xsd_diveplan_convert ();
  }

  diveplan::
  diveplan (const ::xercesc::DOMAttr& a,
            ::xml_schema::flags f,
            ::xml_schema::container* c)
  : ::xml_schema::string (a, f, c)
  {
    _xsd_diveplan_convert ();
  }

  diveplan::
  diveplan (const ::std::string& s,
            const ::xercesc::DOMElement* e,
            ::xml_schema::flags f,
            ::xml_schema::container* c)
  : ::xml_schema::string (s, e, f, c)
  {
    _xsd_diveplan_convert ();
  }

  diveplan* diveplan::
  _clone (::xml_schema::flags f,
          ::xml_schema::container* c) const
  {
    return new class diveplan (*this, f, c);
  }

  diveplan::value diveplan::
  _xsd_diveplan_convert () const
  {
    ::xsd::cxx::tree::enum_comparator< char > c (_xsd_diveplan_literals_);
    const value* i (::std::lower_bound (
                      _xsd_diveplan_indexes_,
                      _xsd_diveplan_indexes_ + 4,
                      *this,
                      c));

    if (i == _xsd_diveplan_indexes_ + 4 || _xsd_diveplan_literals_[*i] != *this)
    {
      throw ::xsd::cxx::tree::unexpected_enumerator < char > (*this);
    }

    return *i;
  }

  const char* const diveplan::
  _xsd_diveplan_literals_[4] =
  {
    "none",
    "table",
    "dive-computer",
    "another-diver"
  };

  const diveplan::value diveplan::
  _xsd_diveplan_indexes_[4] =
  {
    ::streit::diveplan::another_diver,
    ::streit::diveplan::dive_computer,
    ::streit::diveplan::none,
    ::streit::diveplan::table
  };
}

#include <ostream>

namespace streit
{
  ::std::ostream&
  operator<< (::std::ostream& o, diveplan::value i)
  {
    return o << diveplan::_xsd_diveplan_literals_[i];
  }

  ::std::ostream&
  operator<< (::std::ostream& o, const diveplan& i)
  {
    return o << static_cast< const ::xml_schema::string& > (i);
  }
}

#include <istream>
#include <xsd/cxx/xml/sax/std-input-source.hxx>
#include <xsd/cxx/tree/error-handler.hxx>

namespace streit
{
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

