// Copyright (c) 2005-2023 Code Synthesis.
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis gives permission
// to link this program with the Xerces-C++ library (or with modified
// versions of Xerces-C++ that use the same license as Xerces-C++), and
// distribute linked combinations including the two. You must obey the GNU
// General Public License version 2 in all respects for all of the code
// used other than Xerces-C++. If you modify this copy of the program, you
// may extend this exception to your version of the program, but you are
// not obligated to do so. If you do not wish to do so, delete this
// exception statement from your version.
//
// Furthermore, Code Synthesis makes a special exception for the Free/Libre
// and Open Source Software (FLOSS) which is described in the accompanying
// FLOSSE file.
//

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/pre.hxx>

#include "dominance.hxx"

namespace streit
{
  // dominance
  //

  dominance::
  dominance (value v)
  : ::xml_schema::string (_xsd_dominance_literals_[v])
  {
  }

  dominance::
  dominance (const char* v)
  : ::xml_schema::string (v)
  {
  }

  dominance::
  dominance (const ::std::string& v)
  : ::xml_schema::string (v)
  {
  }

  dominance::
  dominance (const ::xml_schema::string& v)
  : ::xml_schema::string (v)
  {
  }

  dominance::
  dominance (const dominance& v,
             ::xml_schema::flags f,
             ::xml_schema::container* c)
  : ::xml_schema::string (v, f, c)
  {
  }

  dominance& dominance::
  operator= (value v)
  {
    static_cast< ::xml_schema::string& > (*this) = 
    ::xml_schema::string (_xsd_dominance_literals_[v]);

    return *this;
  }
}

#include <xsd/cxx/xml/dom/parsing-source.hxx>

namespace streit
{
  // dominance
  //

  dominance::
  dominance (const ::xercesc::DOMElement& e,
             ::xml_schema::flags f,
             ::xml_schema::container* c)
  : ::xml_schema::string (e, f, c)
  {
    _xsd_dominance_convert ();
  }

  dominance::
  dominance (const ::xercesc::DOMAttr& a,
             ::xml_schema::flags f,
             ::xml_schema::container* c)
  : ::xml_schema::string (a, f, c)
  {
    _xsd_dominance_convert ();
  }

  dominance::
  dominance (const ::std::string& s,
             const ::xercesc::DOMElement* e,
             ::xml_schema::flags f,
             ::xml_schema::container* c)
  : ::xml_schema::string (s, e, f, c)
  {
    _xsd_dominance_convert ();
  }

  dominance* dominance::
  _clone (::xml_schema::flags f,
          ::xml_schema::container* c) const
  {
    return new class dominance (*this, f, c);
  }

  dominance::value dominance::
  _xsd_dominance_convert () const
  {
    ::xsd::cxx::tree::enum_comparator< char > c (_xsd_dominance_literals_);
    const value* i (::std::lower_bound (
                      _xsd_dominance_indexes_,
                      _xsd_dominance_indexes_ + 7,
                      *this,
                      c));

    if (i == _xsd_dominance_indexes_ + 7 || _xsd_dominance_literals_[*i] != *this)
    {
      throw ::xsd::cxx::tree::unexpected_enumerator < char > (*this);
    }

    return *i;
  }

  const char* const dominance::
  _xsd_dominance_literals_[7] =
  {
    "undetermined",
    "less-than-1/20",
    "1/20-up-to-1/4",
    "1/4-up-to-1/2",
    "1/2-up-to-3/4",
    "greater-than-3/4",
    "single-individual"
  };

  const dominance::value dominance::
  _xsd_dominance_indexes_[7] =
  {
    ::streit::dominance::cxx_1_2_up_to_3_4,
    ::streit::dominance::cxx_1_20_up_to_1_4,
    ::streit::dominance::cxx_1_4_up_to_1_2,
    ::streit::dominance::greater_than_3_4,
    ::streit::dominance::less_than_1_20,
    ::streit::dominance::single_individual,
    ::streit::dominance::undetermined
  };
}

#include <ostream>

namespace streit
{
  ::std::ostream&
  operator<< (::std::ostream& o, dominance::value i)
  {
    return o << dominance::_xsd_dominance_literals_[i];
  }

  ::std::ostream&
  operator<< (::std::ostream& o, const dominance& i)
  {
    return o << static_cast< const ::xml_schema::string& > (i);
  }
}

#include <istream>
#include <xsd/cxx/xml/sax/std-input-source.hxx>
#include <xsd/cxx/tree/error-handler.hxx>

namespace streit
{
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

