// Copyright (c) 2005-2023 Code Synthesis.
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis gives permission
// to link this program with the Xerces-C++ library (or with modified
// versions of Xerces-C++ that use the same license as Xerces-C++), and
// distribute linked combinations including the two. You must obey the GNU
// General Public License version 2 in all respects for all of the code
// used other than Xerces-C++. If you modify this copy of the program, you
// may extend this exception to your version of the program, but you are
// not obligated to do so. If you do not wish to do so, delete this
// exception statement from your version.
//
// Furthermore, Code Synthesis makes a special exception for the Free/Libre
// and Open Source Software (FLOSS) which is described in the accompanying
// FLOSSE file.
//

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/pre.hxx>

#include "drugType.hxx"

#include "periodicallytaken.hxx"

#include "notesType.hxx"

namespace streit
{
  // drugType
  //

  const drugType::periodicallytaken_optional& drugType::
  periodicallytaken () const
  {
    return this->periodicallytaken_;
  }

  drugType::periodicallytaken_optional& drugType::
  periodicallytaken ()
  {
    return this->periodicallytaken_;
  }

  void drugType::
  periodicallytaken (const periodicallytaken_type& x)
  {
    this->periodicallytaken_.set (x);
  }

  void drugType::
  periodicallytaken (const periodicallytaken_optional& x)
  {
    this->periodicallytaken_ = x;
  }

  void drugType::
  periodicallytaken (::std::unique_ptr< periodicallytaken_type > x)
  {
    this->periodicallytaken_.set (std::move (x));
  }

  const drugType::timespanbeforedive_optional& drugType::
  timespanbeforedive () const
  {
    return this->timespanbeforedive_;
  }

  drugType::timespanbeforedive_optional& drugType::
  timespanbeforedive ()
  {
    return this->timespanbeforedive_;
  }

  void drugType::
  timespanbeforedive (const timespanbeforedive_type& x)
  {
    this->timespanbeforedive_.set (x);
  }

  void drugType::
  timespanbeforedive (const timespanbeforedive_optional& x)
  {
    this->timespanbeforedive_ = x;
  }

  const drugType::notes_optional& drugType::
  notes () const
  {
    return this->notes_;
  }

  drugType::notes_optional& drugType::
  notes ()
  {
    return this->notes_;
  }

  void drugType::
  notes (const notes_type& x)
  {
    this->notes_.set (x);
  }

  void drugType::
  notes (const notes_optional& x)
  {
    this->notes_ = x;
  }

  void drugType::
  notes (::std::unique_ptr< notes_type > x)
  {
    this->notes_.set (std::move (x));
  }
}

#include <xsd/cxx/xml/dom/parsing-source.hxx>

namespace streit
{
  // drugType
  //

  drugType::
  drugType (const name_type& name)
  : ::streit::simpleNamedType (name),
    periodicallytaken_ (this),
    timespanbeforedive_ (this),
    notes_ (this)
  {
  }

  drugType::
  drugType (const drugType& x,
            ::xml_schema::flags f,
            ::xml_schema::container* c)
  : ::streit::simpleNamedType (x, f, c),
    periodicallytaken_ (x.periodicallytaken_, f, this),
    timespanbeforedive_ (x.timespanbeforedive_, f, this),
    notes_ (x.notes_, f, this)
  {
  }

  drugType::
  drugType (const ::xercesc::DOMElement& e,
            ::xml_schema::flags f,
            ::xml_schema::container* c)
  : ::streit::simpleNamedType (e, f | ::xml_schema::flags::base, c),
    periodicallytaken_ (this),
    timespanbeforedive_ (this),
    notes_ (this)
  {
    if ((f & ::xml_schema::flags::base) == 0)
    {
      ::xsd::cxx::xml::dom::parser< char > p (e, true, false, false);
      this->parse (p, f);
    }
  }

  void drugType::
  parse (::xsd::cxx::xml::dom::parser< char >& p,
         ::xml_schema::flags f)
  {
    this->::streit::simpleNamedType::parse (p, f);

    for (; p.more_content (); p.next_content (false))
    {
      const ::xercesc::DOMElement& i (p.cur_element ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      // periodicallytaken
      //
      if (n.name () == "periodicallytaken" && n.namespace_ () == "http://www.streit.cc/uddf/3.2/")
      {
        ::std::unique_ptr< periodicallytaken_type > r (
          periodicallytaken_traits::create (i, f, this));

        if (!this->periodicallytaken_)
        {
          this->periodicallytaken_.set (::std::move (r));
          continue;
        }
      }

      // timespanbeforedive
      //
      if (n.name () == "timespanbeforedive" && n.namespace_ () == "http://www.streit.cc/uddf/3.2/")
      {
        if (!this->timespanbeforedive_)
        {
          this->timespanbeforedive_.set (timespanbeforedive_traits::create (i, f, this));
          continue;
        }
      }

      // notes
      //
      if (n.name () == "notes" && n.namespace_ () == "http://www.streit.cc/uddf/3.2/")
      {
        ::std::unique_ptr< notes_type > r (
          notes_traits::create (i, f, this));

        if (!this->notes_)
        {
          this->notes_.set (::std::move (r));
          continue;
        }
      }

      break;
    }
  }

  drugType* drugType::
  _clone (::xml_schema::flags f,
          ::xml_schema::container* c) const
  {
    return new class drugType (*this, f, c);
  }

  drugType& drugType::
  operator= (const drugType& x)
  {
    if (this != &x)
    {
      static_cast< ::streit::simpleNamedType& > (*this) = x;
      this->periodicallytaken_ = x.periodicallytaken_;
      this->timespanbeforedive_ = x.timespanbeforedive_;
      this->notes_ = x.notes_;
    }

    return *this;
  }

  drugType::
  ~drugType ()
  {
  }
}

#include <ostream>

namespace streit
{
  ::std::ostream&
  operator<< (::std::ostream& o, const drugType& i)
  {
    o << static_cast< const ::streit::simpleNamedType& > (i);

    if (i.periodicallytaken ())
    {
      o << ::std::endl << "periodicallytaken: " << *i.periodicallytaken ();
    }

    if (i.timespanbeforedive ())
    {
      o << ::std::endl << "timespanbeforedive: " << *i.timespanbeforedive ();
    }

    if (i.notes ())
    {
      o << ::std::endl << "notes: " << *i.notes ();
    }

    return o;
  }
}

#include <istream>
#include <xsd/cxx/xml/sax/std-input-source.hxx>
#include <xsd/cxx/tree/error-handler.hxx>

namespace streit
{
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

