// Copyright (c) 2005-2023 Code Synthesis.
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis gives permission
// to link this program with the Xerces-C++ library (or with modified
// versions of Xerces-C++ that use the same license as Xerces-C++), and
// distribute linked combinations including the two. You must obey the GNU
// General Public License version 2 in all respects for all of the code
// used other than Xerces-C++. If you modify this copy of the program, you
// may extend this exception to your version of the program, but you are
// not obligated to do so. If you do not wish to do so, delete this
// exception statement from your version.
//
// Furthermore, Code Synthesis makes a special exception for the Free/Libre
// and Open Source Software (FLOSS) which is described in the accompanying
// FLOSSE file.
//

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/pre.hxx>

#include "encapsulatedDateTimeType.hxx"

namespace streit
{
  // encapsulatedDateTimeType
  //

  const encapsulatedDateTimeType::datetime_type& encapsulatedDateTimeType::
  datetime () const
  {
    return this->datetime_.get ();
  }

  encapsulatedDateTimeType::datetime_type& encapsulatedDateTimeType::
  datetime ()
  {
    return this->datetime_.get ();
  }

  void encapsulatedDateTimeType::
  datetime (const datetime_type& x)
  {
    this->datetime_.set (x);
  }

  void encapsulatedDateTimeType::
  datetime (::std::unique_ptr< datetime_type > x)
  {
    this->datetime_.set (std::move (x));
  }
}

#include <xsd/cxx/xml/dom/parsing-source.hxx>

namespace streit
{
  // encapsulatedDateTimeType
  //

  encapsulatedDateTimeType::
  encapsulatedDateTimeType (const datetime_type& datetime)
  : ::xml_schema::type (),
    datetime_ (datetime, this)
  {
  }

  encapsulatedDateTimeType::
  encapsulatedDateTimeType (const encapsulatedDateTimeType& x,
                            ::xml_schema::flags f,
                            ::xml_schema::container* c)
  : ::xml_schema::type (x, f, c),
    datetime_ (x.datetime_, f, this)
  {
  }

  encapsulatedDateTimeType::
  encapsulatedDateTimeType (const ::xercesc::DOMElement& e,
                            ::xml_schema::flags f,
                            ::xml_schema::container* c)
  : ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
    datetime_ (this)
  {
    if ((f & ::xml_schema::flags::base) == 0)
    {
      ::xsd::cxx::xml::dom::parser< char > p (e, true, false, false);
      this->parse (p, f);
    }
  }

  void encapsulatedDateTimeType::
  parse (::xsd::cxx::xml::dom::parser< char >& p,
         ::xml_schema::flags f)
  {
    for (; p.more_content (); p.next_content (false))
    {
      const ::xercesc::DOMElement& i (p.cur_element ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      // datetime
      //
      if (n.name () == "datetime" && n.namespace_ () == "http://www.streit.cc/uddf/3.2/")
      {
        ::std::unique_ptr< datetime_type > r (
          datetime_traits::create (i, f, this));

        if (!datetime_.present ())
        {
          this->datetime_.set (::std::move (r));
          continue;
        }
      }

      break;
    }

    if (!datetime_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "datetime",
        "http://www.streit.cc/uddf/3.2/");
    }
  }

  encapsulatedDateTimeType* encapsulatedDateTimeType::
  _clone (::xml_schema::flags f,
          ::xml_schema::container* c) const
  {
    return new class encapsulatedDateTimeType (*this, f, c);
  }

  encapsulatedDateTimeType& encapsulatedDateTimeType::
  operator= (const encapsulatedDateTimeType& x)
  {
    if (this != &x)
    {
      static_cast< ::xml_schema::type& > (*this) = x;
      this->datetime_ = x.datetime_;
    }

    return *this;
  }

  encapsulatedDateTimeType::
  ~encapsulatedDateTimeType ()
  {
  }
}

#include <ostream>

namespace streit
{
  ::std::ostream&
  operator<< (::std::ostream& o, const encapsulatedDateTimeType& i)
  {
    o << ::std::endl << "datetime: " << i.datetime ();
    return o;
  }
}

#include <istream>
#include <xsd/cxx/xml/sax/std-input-source.hxx>
#include <xsd/cxx/tree/error-handler.hxx>

namespace streit
{
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

