// Copyright (c) 2005-2023 Code Synthesis.
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis gives permission
// to link this program with the Xerces-C++ library (or with modified
// versions of Xerces-C++ that use the same license as Xerces-C++), and
// distribute linked combinations including the two. You must obey the GNU
// General Public License version 2 in all respects for all of the code
// used other than Xerces-C++. If you modify this copy of the program, you
// may extend this exception to your version of the program, but you are
// not obligated to do so. If you do not wish to do so, delete this
// exception statement from your version.
//
// Furthermore, Code Synthesis makes a special exception for the Free/Libre
// and Open Source Software (FLOSS) which is described in the accompanying
// FLOSSE file.
//

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/pre.hxx>

#include "personType.hxx"

#include "ID.hxx"

#include "personalType.hxx"

#include "addressType.hxx"

#include "contactType.hxx"

#include "equipmentType.hxx"

#include "medical.hxx"

#include "education.hxx"

#include "divepermissions.hxx"

#include "diveinsurances.hxx"

#include "notesType.hxx"

namespace streit
{
  // personType
  //

  const personType::equipment_optional& personType::
  equipment () const
  {
    return this->equipment_;
  }

  personType::equipment_optional& personType::
  equipment ()
  {
    return this->equipment_;
  }

  void personType::
  equipment (const equipment_type& x)
  {
    this->equipment_.set (x);
  }

  void personType::
  equipment (const equipment_optional& x)
  {
    this->equipment_ = x;
  }

  void personType::
  equipment (::std::unique_ptr< equipment_type > x)
  {
    this->equipment_.set (std::move (x));
  }

  const personType::medical_optional& personType::
  medical () const
  {
    return this->medical_;
  }

  personType::medical_optional& personType::
  medical ()
  {
    return this->medical_;
  }

  void personType::
  medical (const medical_type& x)
  {
    this->medical_.set (x);
  }

  void personType::
  medical (const medical_optional& x)
  {
    this->medical_ = x;
  }

  void personType::
  medical (::std::unique_ptr< medical_type > x)
  {
    this->medical_.set (std::move (x));
  }

  const personType::education_optional& personType::
  education () const
  {
    return this->education_;
  }

  personType::education_optional& personType::
  education ()
  {
    return this->education_;
  }

  void personType::
  education (const education_type& x)
  {
    this->education_.set (x);
  }

  void personType::
  education (const education_optional& x)
  {
    this->education_ = x;
  }

  void personType::
  education (::std::unique_ptr< education_type > x)
  {
    this->education_.set (std::move (x));
  }

  const personType::divepermissions_optional& personType::
  divepermissions () const
  {
    return this->divepermissions_;
  }

  personType::divepermissions_optional& personType::
  divepermissions ()
  {
    return this->divepermissions_;
  }

  void personType::
  divepermissions (const divepermissions_type& x)
  {
    this->divepermissions_.set (x);
  }

  void personType::
  divepermissions (const divepermissions_optional& x)
  {
    this->divepermissions_ = x;
  }

  void personType::
  divepermissions (::std::unique_ptr< divepermissions_type > x)
  {
    this->divepermissions_.set (std::move (x));
  }

  const personType::diveinsurances_optional& personType::
  diveinsurances () const
  {
    return this->diveinsurances_;
  }

  personType::diveinsurances_optional& personType::
  diveinsurances ()
  {
    return this->diveinsurances_;
  }

  void personType::
  diveinsurances (const diveinsurances_type& x)
  {
    this->diveinsurances_.set (x);
  }

  void personType::
  diveinsurances (const diveinsurances_optional& x)
  {
    this->diveinsurances_ = x;
  }

  void personType::
  diveinsurances (::std::unique_ptr< diveinsurances_type > x)
  {
    this->diveinsurances_.set (std::move (x));
  }

  const personType::notes_optional& personType::
  notes () const
  {
    return this->notes_;
  }

  personType::notes_optional& personType::
  notes ()
  {
    return this->notes_;
  }

  void personType::
  notes (const notes_type& x)
  {
    this->notes_.set (x);
  }

  void personType::
  notes (const notes_optional& x)
  {
    this->notes_ = x;
  }

  void personType::
  notes (::std::unique_ptr< notes_type > x)
  {
    this->notes_.set (std::move (x));
  }
}

#include <xsd/cxx/xml/dom/parsing-source.hxx>

namespace streit
{
  // personType
  //

  personType::
  personType (const id_type& id,
              const personal_type& personal)
  : ::streit::individualType (id,
                              personal),
    equipment_ (this),
    medical_ (this),
    education_ (this),
    divepermissions_ (this),
    diveinsurances_ (this),
    notes_ (this)
  {
  }

  personType::
  personType (const id_type& id,
              ::std::unique_ptr< personal_type > personal)
  : ::streit::individualType (id,
                              std::move (personal)),
    equipment_ (this),
    medical_ (this),
    education_ (this),
    divepermissions_ (this),
    diveinsurances_ (this),
    notes_ (this)
  {
  }

  personType::
  personType (const personType& x,
              ::xml_schema::flags f,
              ::xml_schema::container* c)
  : ::streit::individualType (x, f, c),
    equipment_ (x.equipment_, f, this),
    medical_ (x.medical_, f, this),
    education_ (x.education_, f, this),
    divepermissions_ (x.divepermissions_, f, this),
    diveinsurances_ (x.diveinsurances_, f, this),
    notes_ (x.notes_, f, this)
  {
  }

  personType::
  personType (const ::xercesc::DOMElement& e,
              ::xml_schema::flags f,
              ::xml_schema::container* c)
  : ::streit::individualType (e, f | ::xml_schema::flags::base, c),
    equipment_ (this),
    medical_ (this),
    education_ (this),
    divepermissions_ (this),
    diveinsurances_ (this),
    notes_ (this)
  {
    if ((f & ::xml_schema::flags::base) == 0)
    {
      ::xsd::cxx::xml::dom::parser< char > p (e, true, false, true);
      this->parse (p, f);
    }
  }

  void personType::
  parse (::xsd::cxx::xml::dom::parser< char >& p,
         ::xml_schema::flags f)
  {
    this->::streit::individualType::parse (p, f);

    for (; p.more_content (); p.next_content (false))
    {
      const ::xercesc::DOMElement& i (p.cur_element ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      // equipment
      //
      if (n.name () == "equipment" && n.namespace_ () == "http://www.streit.cc/uddf/3.2/")
      {
        ::std::unique_ptr< equipment_type > r (
          equipment_traits::create (i, f, this));

        if (!this->equipment_)
        {
          this->equipment_.set (::std::move (r));
          continue;
        }
      }

      // medical
      //
      if (n.name () == "medical" && n.namespace_ () == "http://www.streit.cc/uddf/3.2/")
      {
        ::std::unique_ptr< medical_type > r (
          medical_traits::create (i, f, this));

        if (!this->medical_)
        {
          this->medical_.set (::std::move (r));
          continue;
        }
      }

      // education
      //
      if (n.name () == "education" && n.namespace_ () == "http://www.streit.cc/uddf/3.2/")
      {
        ::std::unique_ptr< education_type > r (
          education_traits::create (i, f, this));

        if (!this->education_)
        {
          this->education_.set (::std::move (r));
          continue;
        }
      }

      // divepermissions
      //
      if (n.name () == "divepermissions" && n.namespace_ () == "http://www.streit.cc/uddf/3.2/")
      {
        ::std::unique_ptr< divepermissions_type > r (
          divepermissions_traits::create (i, f, this));

        if (!this->divepermissions_)
        {
          this->divepermissions_.set (::std::move (r));
          continue;
        }
      }

      // diveinsurances
      //
      if (n.name () == "diveinsurances" && n.namespace_ () == "http://www.streit.cc/uddf/3.2/")
      {
        ::std::unique_ptr< diveinsurances_type > r (
          diveinsurances_traits::create (i, f, this));

        if (!this->diveinsurances_)
        {
          this->diveinsurances_.set (::std::move (r));
          continue;
        }
      }

      // notes
      //
      if (n.name () == "notes" && n.namespace_ () == "http://www.streit.cc/uddf/3.2/")
      {
        ::std::unique_ptr< notes_type > r (
          notes_traits::create (i, f, this));

        if (!this->notes_)
        {
          this->notes_.set (::std::move (r));
          continue;
        }
      }

      break;
    }
  }

  personType* personType::
  _clone (::xml_schema::flags f,
          ::xml_schema::container* c) const
  {
    return new class personType (*this, f, c);
  }

  personType& personType::
  operator= (const personType& x)
  {
    if (this != &x)
    {
      static_cast< ::streit::individualType& > (*this) = x;
      this->equipment_ = x.equipment_;
      this->medical_ = x.medical_;
      this->education_ = x.education_;
      this->divepermissions_ = x.divepermissions_;
      this->diveinsurances_ = x.diveinsurances_;
      this->notes_ = x.notes_;
    }

    return *this;
  }

  personType::
  ~personType ()
  {
  }
}

#include <ostream>

namespace streit
{
  ::std::ostream&
  operator<< (::std::ostream& o, const personType& i)
  {
    o << static_cast< const ::streit::individualType& > (i);

    if (i.equipment ())
    {
      o << ::std::endl << "equipment: " << *i.equipment ();
    }

    if (i.medical ())
    {
      o << ::std::endl << "medical: " << *i.medical ();
    }

    if (i.education ())
    {
      o << ::std::endl << "education: " << *i.education ();
    }

    if (i.divepermissions ())
    {
      o << ::std::endl << "divepermissions: " << *i.divepermissions ();
    }

    if (i.diveinsurances ())
    {
      o << ::std::endl << "diveinsurances: " << *i.diveinsurances ();
    }

    if (i.notes ())
    {
      o << ::std::endl << "notes: " << *i.notes ();
    }

    return o;
  }
}

#include <istream>
#include <xsd/cxx/xml/sax/std-input-source.hxx>
#include <xsd/cxx/tree/error-handler.hxx>

namespace streit
{
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

