// Copyright (c) 2005-2023 Code Synthesis.
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis gives permission
// to link this program with the Xerces-C++ library (or with modified
// versions of Xerces-C++ that use the same license as Xerces-C++), and
// distribute linked combinations including the two. You must obey the GNU
// General Public License version 2 in all respects for all of the code
// used other than Xerces-C++. If you modify this copy of the program, you
// may extend this exception to your version of the program, but you are
// not obligated to do so. If you do not wish to do so, delete this
// exception statement from your version.
//
// Furthermore, Code Synthesis makes a special exception for the Free/Libre
// and Open Source Software (FLOSS) which is described in the accompanying
// FLOSSE file.
//

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/pre.hxx>

#include "priceperdivepackageType.hxx"

#include "currency.hxx"

namespace streit
{
  // priceperdivepackageType
  //

  const priceperdivepackageType::noofdives_optional& priceperdivepackageType::
  noofdives () const
  {
    return this->noofdives_;
  }

  priceperdivepackageType::noofdives_optional& priceperdivepackageType::
  noofdives ()
  {
    return this->noofdives_;
  }

  void priceperdivepackageType::
  noofdives (const noofdives_type& x)
  {
    this->noofdives_.set (x);
  }

  void priceperdivepackageType::
  noofdives (const noofdives_optional& x)
  {
    this->noofdives_ = x;
  }

  void priceperdivepackageType::
  noofdives (::std::unique_ptr< noofdives_type > x)
  {
    this->noofdives_.set (std::move (x));
  }
}

#include <xsd/cxx/xml/dom/parsing-source.hxx>

namespace streit
{
  // priceperdivepackageType
  //

  priceperdivepackageType::
  priceperdivepackageType (const ::xml_schema::float_& _xsd_float__base)
  : ::streit::priceType (_xsd_float__base),
    noofdives_ (this)
  {
  }

  priceperdivepackageType::
  priceperdivepackageType (const priceperdivepackageType& x,
                           ::xml_schema::flags f,
                           ::xml_schema::container* c)
  : ::streit::priceType (x, f, c),
    noofdives_ (x.noofdives_, f, this)
  {
  }

  priceperdivepackageType::
  priceperdivepackageType (const ::xercesc::DOMElement& e,
                           ::xml_schema::flags f,
                           ::xml_schema::container* c)
  : ::streit::priceType (e, f | ::xml_schema::flags::base, c),
    noofdives_ (this)
  {
    if ((f & ::xml_schema::flags::base) == 0)
    {
      ::xsd::cxx::xml::dom::parser< char > p (e, false, false, true);
      this->parse (p, f);
    }
  }

  void priceperdivepackageType::
  parse (::xsd::cxx::xml::dom::parser< char >& p,
         ::xml_schema::flags f)
  {
    this->::streit::priceType::parse (p, f);

    p.reset_attributes ();

    while (p.more_attributes ())
    {
      const ::xercesc::DOMAttr& i (p.next_attribute ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      if (n.name () == "noofdives" && n.namespace_ ().empty ())
      {
        this->noofdives_.set (noofdives_traits::create (i, f, this));
        continue;
      }
    }
  }

  priceperdivepackageType* priceperdivepackageType::
  _clone (::xml_schema::flags f,
          ::xml_schema::container* c) const
  {
    return new class priceperdivepackageType (*this, f, c);
  }

  priceperdivepackageType& priceperdivepackageType::
  operator= (const priceperdivepackageType& x)
  {
    if (this != &x)
    {
      static_cast< ::streit::priceType& > (*this) = x;
      this->noofdives_ = x.noofdives_;
    }

    return *this;
  }

  priceperdivepackageType::
  ~priceperdivepackageType ()
  {
  }
}

#include <ostream>

namespace streit
{
  ::std::ostream&
  operator<< (::std::ostream& o, const priceperdivepackageType& i)
  {
    o << static_cast< const ::streit::priceType& > (i);

    if (i.noofdives ())
    {
      o << ::std::endl << "noofdives: " << *i.noofdives ();
    }

    return o;
  }
}

#include <istream>
#include <xsd/cxx/xml/sax/std-input-source.hxx>
#include <xsd/cxx/tree/error-handler.hxx>

namespace streit
{
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

