// Copyright (c) 2005-2023 Code Synthesis.
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis gives permission
// to link this program with the Xerces-C++ library (or with modified
// versions of Xerces-C++ that use the same license as Xerces-C++), and
// distribute linked combinations including the two. You must obey the GNU
// General Public License version 2 in all respects for all of the code
// used other than Xerces-C++. If you modify this copy of the program, you
// may extend this exception to your version of the program, but you are
// not obligated to do so. If you do not wish to do so, delete this
// exception statement from your version.
//
// Furthermore, Code Synthesis makes a special exception for the Free/Libre
// and Open Source Software (FLOSS) which is described in the accompanying
// FLOSSE file.
//

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/pre.hxx>

#include "singleLifeFormType.hxx"

#include "speciesType.hxx"

namespace streit
{
  // singleLifeFormType
  //

  const singleLifeFormType::species_sequence& singleLifeFormType::
  species () const
  {
    return this->species_;
  }

  singleLifeFormType::species_sequence& singleLifeFormType::
  species ()
  {
    return this->species_;
  }

  void singleLifeFormType::
  species (const species_sequence& s)
  {
    this->species_ = s;
  }
}

#include <xsd/cxx/xml/dom/parsing-source.hxx>

namespace streit
{
  // singleLifeFormType
  //

  singleLifeFormType::
  singleLifeFormType ()
  : ::xml_schema::type (),
    species_ (this)
  {
  }

  singleLifeFormType::
  singleLifeFormType (const singleLifeFormType& x,
                      ::xml_schema::flags f,
                      ::xml_schema::container* c)
  : ::xml_schema::type (x, f, c),
    species_ (x.species_, f, this)
  {
  }

  singleLifeFormType::
  singleLifeFormType (const ::xercesc::DOMElement& e,
                      ::xml_schema::flags f,
                      ::xml_schema::container* c)
  : ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
    species_ (this)
  {
    if ((f & ::xml_schema::flags::base) == 0)
    {
      ::xsd::cxx::xml::dom::parser< char > p (e, true, false, false);
      this->parse (p, f);
    }
  }

  void singleLifeFormType::
  parse (::xsd::cxx::xml::dom::parser< char >& p,
         ::xml_schema::flags f)
  {
    for (; p.more_content (); p.next_content (false))
    {
      const ::xercesc::DOMElement& i (p.cur_element ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      // species
      //
      if (n.name () == "species" && n.namespace_ () == "http://www.streit.cc/uddf/3.2/")
      {
        ::std::unique_ptr< species_type > r (
          species_traits::create (i, f, this));

        this->species_.push_back (::std::move (r));
        continue;
      }

      break;
    }
  }

  singleLifeFormType* singleLifeFormType::
  _clone (::xml_schema::flags f,
          ::xml_schema::container* c) const
  {
    return new class singleLifeFormType (*this, f, c);
  }

  singleLifeFormType& singleLifeFormType::
  operator= (const singleLifeFormType& x)
  {
    if (this != &x)
    {
      static_cast< ::xml_schema::type& > (*this) = x;
      this->species_ = x.species_;
    }

    return *this;
  }

  singleLifeFormType::
  ~singleLifeFormType ()
  {
  }
}

#include <ostream>

namespace streit
{
  ::std::ostream&
  operator<< (::std::ostream& o, const singleLifeFormType& i)
  {
    for (singleLifeFormType::species_const_iterator
         b (i.species ().begin ()), e (i.species ().end ());
         b != e; ++b)
    {
      o << ::std::endl << "species: " << *b;
    }

    return o;
  }
}

#include <istream>
#include <xsd/cxx/xml/sax/std-input-source.hxx>
#include <xsd/cxx/tree/error-handler.hxx>

namespace streit
{
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

