// Copyright (c) 2005-2023 Code Synthesis.
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis gives permission
// to link this program with the Xerces-C++ library (or with modified
// versions of Xerces-C++ that use the same license as Xerces-C++), and
// distribute linked combinations including the two. You must obey the GNU
// General Public License version 2 in all respects for all of the code
// used other than Xerces-C++. If you modify this copy of the program, you
// may extend this exception to your version of the program, but you are
// not obligated to do so. If you do not wish to do so, delete this
// exception statement from your version.
//
// Furthermore, Code Synthesis makes a special exception for the Free/Libre
// and Open Source Software (FLOSS) which is described in the accompanying
// FLOSSE file.
//

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/pre.hxx>

#include "tablegeneration.hxx"

#include "calculateprofile.hxx"

#include "calculatetable.hxx"

#include "calculatebottomtimetable.hxx"

namespace streit
{
  // tablegeneration
  //

  const tablegeneration::calculateprofile_optional& tablegeneration::
  calculateprofile () const
  {
    return this->calculateprofile_;
  }

  tablegeneration::calculateprofile_optional& tablegeneration::
  calculateprofile ()
  {
    return this->calculateprofile_;
  }

  void tablegeneration::
  calculateprofile (const calculateprofile_type& x)
  {
    this->calculateprofile_.set (x);
  }

  void tablegeneration::
  calculateprofile (const calculateprofile_optional& x)
  {
    this->calculateprofile_ = x;
  }

  void tablegeneration::
  calculateprofile (::std::unique_ptr< calculateprofile_type > x)
  {
    this->calculateprofile_.set (std::move (x));
  }

  const tablegeneration::calculatetable_optional& tablegeneration::
  calculatetable () const
  {
    return this->calculatetable_;
  }

  tablegeneration::calculatetable_optional& tablegeneration::
  calculatetable ()
  {
    return this->calculatetable_;
  }

  void tablegeneration::
  calculatetable (const calculatetable_type& x)
  {
    this->calculatetable_.set (x);
  }

  void tablegeneration::
  calculatetable (const calculatetable_optional& x)
  {
    this->calculatetable_ = x;
  }

  void tablegeneration::
  calculatetable (::std::unique_ptr< calculatetable_type > x)
  {
    this->calculatetable_.set (std::move (x));
  }

  const tablegeneration::calculatebottomtimetable_optional& tablegeneration::
  calculatebottomtimetable () const
  {
    return this->calculatebottomtimetable_;
  }

  tablegeneration::calculatebottomtimetable_optional& tablegeneration::
  calculatebottomtimetable ()
  {
    return this->calculatebottomtimetable_;
  }

  void tablegeneration::
  calculatebottomtimetable (const calculatebottomtimetable_type& x)
  {
    this->calculatebottomtimetable_.set (x);
  }

  void tablegeneration::
  calculatebottomtimetable (const calculatebottomtimetable_optional& x)
  {
    this->calculatebottomtimetable_ = x;
  }

  void tablegeneration::
  calculatebottomtimetable (::std::unique_ptr< calculatebottomtimetable_type > x)
  {
    this->calculatebottomtimetable_.set (std::move (x));
  }
}

#include <xsd/cxx/xml/dom/parsing-source.hxx>

namespace streit
{
  // tablegeneration
  //

  tablegeneration::
  tablegeneration ()
  : ::xml_schema::type (),
    calculateprofile_ (this),
    calculatetable_ (this),
    calculatebottomtimetable_ (this)
  {
  }

  tablegeneration::
  tablegeneration (const tablegeneration& x,
                   ::xml_schema::flags f,
                   ::xml_schema::container* c)
  : ::xml_schema::type (x, f, c),
    calculateprofile_ (x.calculateprofile_, f, this),
    calculatetable_ (x.calculatetable_, f, this),
    calculatebottomtimetable_ (x.calculatebottomtimetable_, f, this)
  {
  }

  tablegeneration::
  tablegeneration (const ::xercesc::DOMElement& e,
                   ::xml_schema::flags f,
                   ::xml_schema::container* c)
  : ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
    calculateprofile_ (this),
    calculatetable_ (this),
    calculatebottomtimetable_ (this)
  {
    if ((f & ::xml_schema::flags::base) == 0)
    {
      ::xsd::cxx::xml::dom::parser< char > p (e, true, false, false);
      this->parse (p, f);
    }
  }

  void tablegeneration::
  parse (::xsd::cxx::xml::dom::parser< char >& p,
         ::xml_schema::flags f)
  {
    for (; p.more_content (); p.next_content (false))
    {
      const ::xercesc::DOMElement& i (p.cur_element ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      // calculateprofile
      //
      if (n.name () == "calculateprofile" && n.namespace_ () == "http://www.streit.cc/uddf/3.2/")
      {
        ::std::unique_ptr< calculateprofile_type > r (
          calculateprofile_traits::create (i, f, this));

        if (!this->calculateprofile_)
        {
          this->calculateprofile_.set (::std::move (r));
          continue;
        }
      }

      // calculatetable
      //
      if (n.name () == "calculatetable" && n.namespace_ () == "http://www.streit.cc/uddf/3.2/")
      {
        ::std::unique_ptr< calculatetable_type > r (
          calculatetable_traits::create (i, f, this));

        if (!this->calculatetable_)
        {
          this->calculatetable_.set (::std::move (r));
          continue;
        }
      }

      // calculatebottomtimetable
      //
      if (n.name () == "calculatebottomtimetable" && n.namespace_ () == "http://www.streit.cc/uddf/3.2/")
      {
        ::std::unique_ptr< calculatebottomtimetable_type > r (
          calculatebottomtimetable_traits::create (i, f, this));

        if (!this->calculatebottomtimetable_)
        {
          this->calculatebottomtimetable_.set (::std::move (r));
          continue;
        }
      }

      break;
    }
  }

  tablegeneration* tablegeneration::
  _clone (::xml_schema::flags f,
          ::xml_schema::container* c) const
  {
    return new class tablegeneration (*this, f, c);
  }

  tablegeneration& tablegeneration::
  operator= (const tablegeneration& x)
  {
    if (this != &x)
    {
      static_cast< ::xml_schema::type& > (*this) = x;
      this->calculateprofile_ = x.calculateprofile_;
      this->calculatetable_ = x.calculatetable_;
      this->calculatebottomtimetable_ = x.calculatebottomtimetable_;
    }

    return *this;
  }

  tablegeneration::
  ~tablegeneration ()
  {
  }
}

#include <ostream>

namespace streit
{
  ::std::ostream&
  operator<< (::std::ostream& o, const tablegeneration& i)
  {
    if (i.calculateprofile ())
    {
      o << ::std::endl << "calculateprofile: " << *i.calculateprofile ();
    }

    if (i.calculatetable ())
    {
      o << ::std::endl << "calculatetable: " << *i.calculatetable ();
    }

    if (i.calculatebottomtimetable ())
    {
      o << ::std::endl << "calculatebottomtimetable: " << *i.calculatebottomtimetable ();
    }

    return o;
  }
}

#include <istream>
#include <xsd/cxx/xml/sax/std-input-source.hxx>
#include <xsd/cxx/tree/error-handler.hxx>

namespace streit
{
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

