// Copyright (c) 2005-2023 Code Synthesis.
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis gives permission
// to link this program with the Xerces-C++ library (or with modified
// versions of Xerces-C++ that use the same license as Xerces-C++), and
// distribute linked combinations including the two. You must obey the GNU
// General Public License version 2 in all respects for all of the code
// used other than Xerces-C++. If you modify this copy of the program, you
// may extend this exception to your version of the program, but you are
// not obligated to do so. If you do not wish to do so, delete this
// exception statement from your version.
//
// Furthermore, Code Synthesis makes a special exception for the Free/Libre
// and Open Source Software (FLOSS) which is described in the accompanying
// FLOSSE file.
//

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/pre.hxx>

#include "tableType.hxx"

#include "ID.hxx"

#include "linkType.hxx"

#include "surfaceintervalType.hxx"

#include "outputType.hxx"

#include "applicationdataType.hxx"

#include "mixchangeType.hxx"

#include "inputprofileType.hxx"

#include "tablescopeType.hxx"

namespace streit
{
  // tableType
  //

  const tableType::tablescope_type& tableType::
  tablescope () const
  {
    return this->tablescope_.get ();
  }

  tableType::tablescope_type& tableType::
  tablescope ()
  {
    return this->tablescope_.get ();
  }

  void tableType::
  tablescope (const tablescope_type& x)
  {
    this->tablescope_.set (x);
  }

  void tableType::
  tablescope (::std::unique_ptr< tablescope_type > x)
  {
    this->tablescope_.set (std::move (x));
  }
}

#include <xsd/cxx/xml/dom/parsing-source.hxx>

namespace streit
{
  // tableType
  //

  tableType::
  tableType (const id_type& id,
             const tablescope_type& tablescope)
  : ::streit::baseCalculationType (id),
    tablescope_ (tablescope, this)
  {
  }

  tableType::
  tableType (const id_type& id,
             ::std::unique_ptr< tablescope_type > tablescope)
  : ::streit::baseCalculationType (id),
    tablescope_ (std::move (tablescope), this)
  {
  }

  tableType::
  tableType (const tableType& x,
             ::xml_schema::flags f,
             ::xml_schema::container* c)
  : ::streit::baseCalculationType (x, f, c),
    tablescope_ (x.tablescope_, f, this)
  {
  }

  tableType::
  tableType (const ::xercesc::DOMElement& e,
             ::xml_schema::flags f,
             ::xml_schema::container* c)
  : ::streit::baseCalculationType (e, f | ::xml_schema::flags::base, c),
    tablescope_ (this)
  {
    if ((f & ::xml_schema::flags::base) == 0)
    {
      ::xsd::cxx::xml::dom::parser< char > p (e, true, false, true);
      this->parse (p, f);
    }
  }

  void tableType::
  parse (::xsd::cxx::xml::dom::parser< char >& p,
         ::xml_schema::flags f)
  {
    this->::streit::baseCalculationType::parse (p, f);

    for (; p.more_content (); p.next_content (false))
    {
      const ::xercesc::DOMElement& i (p.cur_element ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      // tablescope
      //
      if (n.name () == "tablescope" && n.namespace_ () == "http://www.streit.cc/uddf/3.2/")
      {
        ::std::unique_ptr< tablescope_type > r (
          tablescope_traits::create (i, f, this));

        if (!tablescope_.present ())
        {
          this->tablescope_.set (::std::move (r));
          continue;
        }
      }

      break;
    }

    if (!tablescope_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "tablescope",
        "http://www.streit.cc/uddf/3.2/");
    }
  }

  tableType* tableType::
  _clone (::xml_schema::flags f,
          ::xml_schema::container* c) const
  {
    return new class tableType (*this, f, c);
  }

  tableType& tableType::
  operator= (const tableType& x)
  {
    if (this != &x)
    {
      static_cast< ::streit::baseCalculationType& > (*this) = x;
      this->tablescope_ = x.tablescope_;
    }

    return *this;
  }

  tableType::
  ~tableType ()
  {
  }
}

#include <ostream>

namespace streit
{
  ::std::ostream&
  operator<< (::std::ostream& o, const tableType& i)
  {
    o << static_cast< const ::streit::baseCalculationType& > (i);

    o << ::std::endl << "tablescope: " << i.tablescope ();
    return o;
  }
}

#include <istream>
#include <xsd/cxx/xml/sax/std-input-source.hxx>
#include <xsd/cxx/tree/error-handler.hxx>

namespace streit
{
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

