// Copyright (c) 2005-2023 Code Synthesis.
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis gives permission
// to link this program with the Xerces-C++ library (or with modified
// versions of Xerces-C++ that use the same license as Xerces-C++), and
// distribute linked combinations including the two. You must obey the GNU
// General Public License version 2 in all respects for all of the code
// used other than Xerces-C++. If you modify this copy of the program, you
// may extend this exception to your version of the program, but you are
// not obligated to do so. If you do not wish to do so, delete this
// exception statement from your version.
//
// Furthermore, Code Synthesis makes a special exception for the Free/Libre
// and Open Source Software (FLOSS) which is described in the accompanying
// FLOSSE file.
//

#ifndef BATTERYCHARGECONDITION_HXX
#define BATTERYCHARGECONDITION_HXX

#include "batterychargecondition-fwd.hxx"

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/config.hxx>

#if (LIBXSD_VERSION != 400002000000000L)
#error XSD runtime version mismatch
#endif

#include <xsd/cxx/pre.hxx>

#include <memory>    // ::std::unique_ptr
#include <limits>    // std::numeric_limits
#include <algorithm> // std::binary_search
#include <utility>   // std::move

#include <xsd/cxx/xml/char-utf8.hxx>

#include <xsd/cxx/tree/exceptions.hxx>
#include <xsd/cxx/tree/elements.hxx>
#include <xsd/cxx/tree/containers.hxx>
#include <xsd/cxx/tree/list.hxx>

#include <xsd/cxx/xml/dom/parsing-header.hxx>

#include "IDREF-fwd.hxx"

namespace streit
{
  class batterychargecondition: public ::xsd::cxx::tree::fundamental_base< ::xml_schema::float_, char, ::xml_schema::simple_type >
  {
    public:
    // deviceref
    //
    typedef ::streit::IDREF deviceref_type;
    typedef ::xsd::cxx::tree::traits< deviceref_type, char > deviceref_traits;

    const deviceref_type&
    deviceref () const;

    deviceref_type&
    deviceref ();

    void
    deviceref (const deviceref_type& x);

    void
    deviceref (::std::unique_ptr< deviceref_type > p);

    // tankref
    //
    typedef ::streit::IDREF tankref_type;
    typedef ::xsd::cxx::tree::optional< tankref_type > tankref_optional;
    typedef ::xsd::cxx::tree::traits< tankref_type, char > tankref_traits;

    const tankref_optional&
    tankref () const;

    tankref_optional&
    tankref ();

    void
    tankref (const tankref_type& x);

    void
    tankref (const tankref_optional& x);

    void
    tankref (::std::unique_ptr< tankref_type > p);

    // Constructors.
    //
    batterychargecondition (const ::xml_schema::float_&,
                            const deviceref_type&);

    batterychargecondition (const ::xercesc::DOMElement& e,
                            ::xml_schema::flags f = 0,
                            ::xml_schema::container* c = 0);

    batterychargecondition (const batterychargecondition& x,
                            ::xml_schema::flags f = 0,
                            ::xml_schema::container* c = 0);

    virtual batterychargecondition*
    _clone (::xml_schema::flags f = 0,
            ::xml_schema::container* c = 0) const;

    batterychargecondition&
    operator= (const batterychargecondition& x);

    virtual 
    ~batterychargecondition ();

    // Implementation.
    //
    protected:
    void
    parse (::xsd::cxx::xml::dom::parser< char >&,
           ::xml_schema::flags);

    protected:
    ::xsd::cxx::tree::one< deviceref_type > deviceref_;
    tankref_optional tankref_;
  };
}

#include <iosfwd>

namespace streit
{
  ::std::ostream&
  operator<< (::std::ostream&, const batterychargecondition&);
}

#include <iosfwd>

#include <xercesc/sax/InputSource.hpp>
#include <xercesc/dom/DOMDocument.hpp>
#include <xercesc/dom/DOMErrorHandler.hpp>

namespace streit
{
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

#endif // BATTERYCHARGECONDITION_HXX
