// Copyright (c) 2005-2023 Code Synthesis.
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis gives permission
// to link this program with the Xerces-C++ library (or with modified
// versions of Xerces-C++ that use the same license as Xerces-C++), and
// distribute linked combinations including the two. You must obey the GNU
// General Public License version 2 in all respects for all of the code
// used other than Xerces-C++. If you modify this copy of the program, you
// may extend this exception to your version of the program, but you are
// not obligated to do so. If you do not wish to do so, delete this
// exception statement from your version.
//
// Furthermore, Code Synthesis makes a special exception for the Free/Libre
// and Open Source Software (FLOSS) which is described in the accompanying
// FLOSSE file.
//

#ifndef CAMERA_TYPE_HXX
#define CAMERA_TYPE_HXX

#include "cameraType-fwd.hxx"

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/config.hxx>

#if (LIBXSD_VERSION != 400002000000000L)
#error XSD runtime version mismatch
#endif

#include <xsd/cxx/pre.hxx>

#include <memory>    // ::std::unique_ptr
#include <limits>    // std::numeric_limits
#include <algorithm> // std::binary_search
#include <utility>   // std::move

#include <xsd/cxx/xml/char-utf8.hxx>

#include <xsd/cxx/tree/exceptions.hxx>
#include <xsd/cxx/tree/elements.hxx>
#include <xsd/cxx/tree/containers.hxx>
#include <xsd/cxx/tree/list.hxx>

#include <xsd/cxx/xml/dom/parsing-header.hxx>

#include "ID_TYPE.hxx"

#include "equipmentPieceType-fwd.hxx"

namespace streit
{
  class cameraType: public ::streit::ID_TYPE
  {
    public:
    // body
    //
    typedef ::streit::equipmentPieceType body_type;
    typedef ::xsd::cxx::tree::sequence< body_type > body_sequence;
    typedef body_sequence::iterator body_iterator;
    typedef body_sequence::const_iterator body_const_iterator;
    typedef ::xsd::cxx::tree::traits< body_type, char > body_traits;

    const body_sequence&
    body () const;

    body_sequence&
    body ();

    void
    body (const body_sequence& s);

    // lens
    //
    typedef ::streit::equipmentPieceType lens_type;
    typedef ::xsd::cxx::tree::sequence< lens_type > lens_sequence;
    typedef lens_sequence::iterator lens_iterator;
    typedef lens_sequence::const_iterator lens_const_iterator;
    typedef ::xsd::cxx::tree::traits< lens_type, char > lens_traits;

    const lens_sequence&
    lens () const;

    lens_sequence&
    lens ();

    void
    lens (const lens_sequence& s);

    // housing
    //
    typedef ::streit::equipmentPieceType housing_type;
    typedef ::xsd::cxx::tree::sequence< housing_type > housing_sequence;
    typedef housing_sequence::iterator housing_iterator;
    typedef housing_sequence::const_iterator housing_const_iterator;
    typedef ::xsd::cxx::tree::traits< housing_type, char > housing_traits;

    const housing_sequence&
    housing () const;

    housing_sequence&
    housing ();

    void
    housing (const housing_sequence& s);

    // flash
    //
    typedef ::streit::equipmentPieceType flash_type;
    typedef ::xsd::cxx::tree::sequence< flash_type > flash_sequence;
    typedef flash_sequence::iterator flash_iterator;
    typedef flash_sequence::const_iterator flash_const_iterator;
    typedef ::xsd::cxx::tree::traits< flash_type, char > flash_traits;

    const flash_sequence&
    flash () const;

    flash_sequence&
    flash ();

    void
    flash (const flash_sequence& s);

    // Constructors.
    //
    cameraType (const id_type&);

    cameraType (const ::xercesc::DOMElement& e,
                ::xml_schema::flags f = 0,
                ::xml_schema::container* c = 0);

    cameraType (const cameraType& x,
                ::xml_schema::flags f = 0,
                ::xml_schema::container* c = 0);

    virtual cameraType*
    _clone (::xml_schema::flags f = 0,
            ::xml_schema::container* c = 0) const;

    cameraType&
    operator= (const cameraType& x);

    virtual 
    ~cameraType ();

    // Implementation.
    //
    protected:
    void
    parse (::xsd::cxx::xml::dom::parser< char >&,
           ::xml_schema::flags);

    protected:
    body_sequence body_;
    lens_sequence lens_;
    housing_sequence housing_;
    flash_sequence flash_;
  };
}

#include <iosfwd>

namespace streit
{
  ::std::ostream&
  operator<< (::std::ostream&, const cameraType&);
}

#include <iosfwd>

#include <xercesc/sax/InputSource.hpp>
#include <xercesc/dom/DOMDocument.hpp>
#include <xercesc/dom/DOMErrorHandler.hpp>

namespace streit
{
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

#endif // CAMERA_TYPE_HXX
