// Copyright (c) 2005-2023 Code Synthesis.
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis gives permission
// to link this program with the Xerces-C++ library (or with modified
// versions of Xerces-C++ that use the same license as Xerces-C++), and
// distribute linked combinations including the two. You must obey the GNU
// General Public License version 2 in all respects for all of the code
// used other than Xerces-C++. If you modify this copy of the program, you
// may extend this exception to your version of the program, but you are
// not obligated to do so. If you do not wish to do so, delete this
// exception statement from your version.
//
// Furthermore, Code Synthesis makes a special exception for the Free/Libre
// and Open Source Software (FLOSS) which is described in the accompanying
// FLOSSE file.
//

#ifndef DCALARM_WITH_DEPTH_TYPE_HXX
#define DCALARM_WITH_DEPTH_TYPE_HXX

#include "dcalarmWithDepthType-fwd.hxx"

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/config.hxx>

#if (LIBXSD_VERSION != 400002000000000L)
#error XSD runtime version mismatch
#endif

#include <xsd/cxx/pre.hxx>

#include <memory>    // ::std::unique_ptr
#include <limits>    // std::numeric_limits
#include <algorithm> // std::binary_search
#include <utility>   // std::move

#include <xsd/cxx/xml/char-utf8.hxx>

#include <xsd/cxx/tree/exceptions.hxx>
#include <xsd/cxx/tree/elements.hxx>
#include <xsd/cxx/tree/containers.hxx>
#include <xsd/cxx/tree/list.hxx>

#include <xsd/cxx/xml/dom/parsing-header.hxx>

#include "dcalarmType-fwd.hxx"

namespace streit
{
  class dcalarmWithDepthType: public ::xml_schema::type
  {
    public:
    // dcalarmdepth
    //
    typedef ::xml_schema::float_ dcalarmdepth_type;
    typedef ::xsd::cxx::tree::traits< dcalarmdepth_type, char > dcalarmdepth_traits;

    const dcalarmdepth_type&
    dcalarmdepth () const;

    dcalarmdepth_type&
    dcalarmdepth ();

    void
    dcalarmdepth (const dcalarmdepth_type& x);

    // dcalarm
    //
    typedef ::streit::dcalarmType dcalarm_type;
    typedef ::xsd::cxx::tree::traits< dcalarm_type, char > dcalarm_traits;

    const dcalarm_type&
    dcalarm () const;

    dcalarm_type&
    dcalarm ();

    void
    dcalarm (const dcalarm_type& x);

    void
    dcalarm (::std::unique_ptr< dcalarm_type > p);

    // Constructors.
    //
    dcalarmWithDepthType (const dcalarmdepth_type&,
                          const dcalarm_type&);

    dcalarmWithDepthType (const dcalarmdepth_type&,
                          ::std::unique_ptr< dcalarm_type >);

    dcalarmWithDepthType (const ::xercesc::DOMElement& e,
                          ::xml_schema::flags f = 0,
                          ::xml_schema::container* c = 0);

    dcalarmWithDepthType (const dcalarmWithDepthType& x,
                          ::xml_schema::flags f = 0,
                          ::xml_schema::container* c = 0);

    virtual dcalarmWithDepthType*
    _clone (::xml_schema::flags f = 0,
            ::xml_schema::container* c = 0) const;

    dcalarmWithDepthType&
    operator= (const dcalarmWithDepthType& x);

    virtual 
    ~dcalarmWithDepthType ();

    // Implementation.
    //
    protected:
    void
    parse (::xsd::cxx::xml::dom::parser< char >&,
           ::xml_schema::flags);

    protected:
    ::xsd::cxx::tree::one< dcalarmdepth_type > dcalarmdepth_;
    ::xsd::cxx::tree::one< dcalarm_type > dcalarm_;
  };
}

#include <iosfwd>

namespace streit
{
  ::std::ostream&
  operator<< (::std::ostream&, const dcalarmWithDepthType&);
}

#include <iosfwd>

#include <xercesc/sax/InputSource.hpp>
#include <xercesc/dom/DOMDocument.hpp>
#include <xercesc/dom/DOMErrorHandler.hpp>

namespace streit
{
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

#endif // DCALARM_WITH_DEPTH_TYPE_HXX
