// Copyright (c) 2005-2023 Code Synthesis.
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis gives permission
// to link this program with the Xerces-C++ library (or with modified
// versions of Xerces-C++ that use the same license as Xerces-C++), and
// distribute linked combinations including the two. You must obey the GNU
// General Public License version 2 in all respects for all of the code
// used other than Xerces-C++. If you modify this copy of the program, you
// may extend this exception to your version of the program, but you are
// not obligated to do so. If you do not wish to do so, delete this
// exception statement from your version.
//
// Furthermore, Code Synthesis makes a special exception for the Free/Libre
// and Open Source Software (FLOSS) which is described in the accompanying
// FLOSSE file.
//

#ifndef DCALARMTIME_TYPE_HXX
#define DCALARMTIME_TYPE_HXX

#include "dcalarmtimeType-fwd.hxx"

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/config.hxx>

#if (LIBXSD_VERSION != 400002000000000L)
#error XSD runtime version mismatch
#endif

#include <xsd/cxx/pre.hxx>

#include <memory>    // ::std::unique_ptr
#include <limits>    // std::numeric_limits
#include <algorithm> // std::binary_search
#include <utility>   // std::move

#include <xsd/cxx/xml/char-utf8.hxx>

#include <xsd/cxx/tree/exceptions.hxx>
#include <xsd/cxx/tree/elements.hxx>
#include <xsd/cxx/tree/containers.hxx>
#include <xsd/cxx/tree/list.hxx>

#include <xsd/cxx/xml/dom/parsing-header.hxx>

#include "acknowledge-fwd.hxx"

namespace streit
{
  class dcalarmtimeType: public ::xml_schema::type
  {
    public:
    // acknowledge
    //
    typedef ::streit::acknowledge acknowledge_type;
    typedef ::xsd::cxx::tree::optional< acknowledge_type > acknowledge_optional;
    typedef ::xsd::cxx::tree::traits< acknowledge_type, char > acknowledge_traits;

    const acknowledge_optional&
    acknowledge () const;

    acknowledge_optional&
    acknowledge ();

    void
    acknowledge (const acknowledge_type& x);

    void
    acknowledge (const acknowledge_optional& x);

    void
    acknowledge (::std::unique_ptr< acknowledge_type > p);

    // period
    //
    typedef ::xml_schema::float_ period_type;
    typedef ::xsd::cxx::tree::optional< period_type > period_optional;
    typedef ::xsd::cxx::tree::traits< period_type, char > period_traits;

    const period_optional&
    period () const;

    period_optional&
    period ();

    void
    period (const period_type& x);

    void
    period (const period_optional& x);

    // alarmType
    //
    typedef ::xml_schema::unsigned_short alarmType_type;
    typedef ::xsd::cxx::tree::traits< alarmType_type, char > alarmType_traits;

    const alarmType_type&
    alarmType () const;

    alarmType_type&
    alarmType ();

    void
    alarmType (const alarmType_type& x);

    // Constructors.
    //
    dcalarmtimeType (const alarmType_type&);

    dcalarmtimeType (const ::xercesc::DOMElement& e,
                     ::xml_schema::flags f = 0,
                     ::xml_schema::container* c = 0);

    dcalarmtimeType (const dcalarmtimeType& x,
                     ::xml_schema::flags f = 0,
                     ::xml_schema::container* c = 0);

    virtual dcalarmtimeType*
    _clone (::xml_schema::flags f = 0,
            ::xml_schema::container* c = 0) const;

    dcalarmtimeType&
    operator= (const dcalarmtimeType& x);

    virtual 
    ~dcalarmtimeType ();

    // Implementation.
    //
    protected:
    void
    parse (::xsd::cxx::xml::dom::parser< char >&,
           ::xml_schema::flags);

    protected:
    acknowledge_optional acknowledge_;
    period_optional period_;
    ::xsd::cxx::tree::one< alarmType_type > alarmType_;
  };
}

#include <iosfwd>

namespace streit
{
  ::std::ostream&
  operator<< (::std::ostream&, const dcalarmtimeType&);
}

#include <iosfwd>

#include <xercesc/sax/InputSource.hpp>
#include <xercesc/dom/DOMDocument.hpp>
#include <xercesc/dom/DOMErrorHandler.hpp>

namespace streit
{
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

#endif // DCALARMTIME_TYPE_HXX
