// Copyright (c) 2005-2023 Code Synthesis.
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis gives permission
// to link this program with the Xerces-C++ library (or with modified
// versions of Xerces-C++ that use the same license as Xerces-C++), and
// distribute linked combinations including the two. You must obey the GNU
// General Public License version 2 in all respects for all of the code
// used other than Xerces-C++. If you modify this copy of the program, you
// may extend this exception to your version of the program, but you are
// not obligated to do so. If you do not wish to do so, delete this
// exception statement from your version.
//
// Furthermore, Code Synthesis makes a special exception for the Free/Libre
// and Open Source Software (FLOSS) which is described in the accompanying
// FLOSSE file.
//

#ifndef DIVESITE_HXX
#define DIVESITE_HXX

#include "divesite-fwd.hxx"

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/config.hxx>

#if (LIBXSD_VERSION != 400002000000000L)
#error XSD runtime version mismatch
#endif

#include <xsd/cxx/pre.hxx>

#include <memory>    // ::std::unique_ptr
#include <limits>    // std::numeric_limits
#include <algorithm> // std::binary_search
#include <utility>   // std::move

#include <xsd/cxx/xml/char-utf8.hxx>

#include <xsd/cxx/tree/exceptions.hxx>
#include <xsd/cxx/tree/elements.hxx>
#include <xsd/cxx/tree/containers.hxx>
#include <xsd/cxx/tree/list.hxx>

#include <xsd/cxx/xml/dom/parsing-header.hxx>

#include "divebaseType-fwd.hxx"

#include "siteType-fwd.hxx"

namespace streit
{
  class divesite: public ::xml_schema::type
  {
    public:
    // divebase
    //
    typedef ::streit::divebaseType divebase_type;
    typedef ::xsd::cxx::tree::sequence< divebase_type > divebase_sequence;
    typedef divebase_sequence::iterator divebase_iterator;
    typedef divebase_sequence::const_iterator divebase_const_iterator;
    typedef ::xsd::cxx::tree::traits< divebase_type, char > divebase_traits;

    const divebase_sequence&
    divebase () const;

    divebase_sequence&
    divebase ();

    void
    divebase (const divebase_sequence& s);

    // site
    //
    typedef ::streit::siteType site_type;
    typedef ::xsd::cxx::tree::sequence< site_type > site_sequence;
    typedef site_sequence::iterator site_iterator;
    typedef site_sequence::const_iterator site_const_iterator;
    typedef ::xsd::cxx::tree::traits< site_type, char > site_traits;

    const site_sequence&
    site () const;

    site_sequence&
    site ();

    void
    site (const site_sequence& s);

    // Constructors.
    //
    divesite ();

    divesite (const ::xercesc::DOMElement& e,
              ::xml_schema::flags f = 0,
              ::xml_schema::container* c = 0);

    divesite (const divesite& x,
              ::xml_schema::flags f = 0,
              ::xml_schema::container* c = 0);

    virtual divesite*
    _clone (::xml_schema::flags f = 0,
            ::xml_schema::container* c = 0) const;

    divesite&
    operator= (const divesite& x);

    virtual 
    ~divesite ();

    // Implementation.
    //
    protected:
    void
    parse (::xsd::cxx::xml::dom::parser< char >&,
           ::xml_schema::flags);

    protected:
    divebase_sequence divebase_;
    site_sequence site_;
  };
}

#include <iosfwd>

namespace streit
{
  ::std::ostream&
  operator<< (::std::ostream&, const divesite&);
}

#include <iosfwd>

#include <xercesc/sax/InputSource.hpp>
#include <xercesc/dom/DOMDocument.hpp>
#include <xercesc/dom/DOMErrorHandler.hpp>

namespace streit
{
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

#endif // DIVESITE_HXX
