// Copyright (c) 2005-2023 Code Synthesis.
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis gives permission
// to link this program with the Xerces-C++ library (or with modified
// versions of Xerces-C++ that use the same license as Xerces-C++), and
// distribute linked combinations including the two. You must obey the GNU
// General Public License version 2 in all respects for all of the code
// used other than Xerces-C++. If you modify this copy of the program, you
// may extend this exception to your version of the program, but you are
// not obligated to do so. If you do not wish to do so, delete this
// exception statement from your version.
//
// Furthermore, Code Synthesis makes a special exception for the Free/Libre
// and Open Source Software (FLOSS) which is described in the accompanying
// FLOSSE file.
//

#ifndef EXAMINATION_TYPE_HXX
#define EXAMINATION_TYPE_HXX

#include "examinationType-fwd.hxx"

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/config.hxx>

#if (LIBXSD_VERSION != 400002000000000L)
#error XSD runtime version mismatch
#endif

#include <xsd/cxx/pre.hxx>

#include <memory>    // ::std::unique_ptr
#include <limits>    // std::numeric_limits
#include <algorithm> // std::binary_search
#include <utility>   // std::move

#include <xsd/cxx/xml/char-utf8.hxx>

#include <xsd/cxx/tree/exceptions.hxx>
#include <xsd/cxx/tree/elements.hxx>
#include <xsd/cxx/tree/containers.hxx>
#include <xsd/cxx/tree/list.hxx>

#include <xsd/cxx/xml/dom/parsing-header.hxx>

#include "individualType-fwd.hxx"

#include "linkType-fwd.hxx"

#include "examinationresult-fwd.hxx"

#include "notesType-fwd.hxx"

namespace streit
{
  class examinationType: public ::xml_schema::type
  {
    public:
    // datetime
    //
    typedef ::xml_schema::date_time datetime_type;
    typedef ::xsd::cxx::tree::optional< datetime_type > datetime_optional;
    typedef ::xsd::cxx::tree::traits< datetime_type, char > datetime_traits;

    const datetime_optional&
    datetime () const;

    datetime_optional&
    datetime ();

    void
    datetime (const datetime_type& x);

    void
    datetime (const datetime_optional& x);

    void
    datetime (::std::unique_ptr< datetime_type > p);

    // doctor
    //
    typedef ::streit::individualType doctor_type;
    typedef ::xsd::cxx::tree::optional< doctor_type > doctor_optional;
    typedef ::xsd::cxx::tree::traits< doctor_type, char > doctor_traits;

    const doctor_optional&
    doctor () const;

    doctor_optional&
    doctor ();

    void
    doctor (const doctor_type& x);

    void
    doctor (const doctor_optional& x);

    void
    doctor (::std::unique_ptr< doctor_type > p);

    // link
    //
    typedef ::streit::linkType link_type;
    typedef ::xsd::cxx::tree::optional< link_type > link_optional;
    typedef ::xsd::cxx::tree::traits< link_type, char > link_traits;

    const link_optional&
    link () const;

    link_optional&
    link ();

    void
    link (const link_type& x);

    void
    link (const link_optional& x);

    void
    link (::std::unique_ptr< link_type > p);

    // examinationresult
    //
    typedef ::streit::examinationresult examinationresult_type;
    typedef ::xsd::cxx::tree::optional< examinationresult_type > examinationresult_optional;
    typedef ::xsd::cxx::tree::traits< examinationresult_type, char > examinationresult_traits;

    const examinationresult_optional&
    examinationresult () const;

    examinationresult_optional&
    examinationresult ();

    void
    examinationresult (const examinationresult_type& x);

    void
    examinationresult (const examinationresult_optional& x);

    void
    examinationresult (::std::unique_ptr< examinationresult_type > p);

    // totallungcapacity
    //
    typedef ::xml_schema::float_ totallungcapacity_type;
    typedef ::xsd::cxx::tree::optional< totallungcapacity_type > totallungcapacity_optional;
    typedef ::xsd::cxx::tree::traits< totallungcapacity_type, char > totallungcapacity_traits;

    const totallungcapacity_optional&
    totallungcapacity () const;

    totallungcapacity_optional&
    totallungcapacity ();

    void
    totallungcapacity (const totallungcapacity_type& x);

    void
    totallungcapacity (const totallungcapacity_optional& x);

    // vitalcapacity
    //
    typedef ::xml_schema::float_ vitalcapacity_type;
    typedef ::xsd::cxx::tree::optional< vitalcapacity_type > vitalcapacity_optional;
    typedef ::xsd::cxx::tree::traits< vitalcapacity_type, char > vitalcapacity_traits;

    const vitalcapacity_optional&
    vitalcapacity () const;

    vitalcapacity_optional&
    vitalcapacity ();

    void
    vitalcapacity (const vitalcapacity_type& x);

    void
    vitalcapacity (const vitalcapacity_optional& x);

    // notes
    //
    typedef ::streit::notesType notes_type;
    typedef ::xsd::cxx::tree::optional< notes_type > notes_optional;
    typedef ::xsd::cxx::tree::traits< notes_type, char > notes_traits;

    const notes_optional&
    notes () const;

    notes_optional&
    notes ();

    void
    notes (const notes_type& x);

    void
    notes (const notes_optional& x);

    void
    notes (::std::unique_ptr< notes_type > p);

    // Constructors.
    //
    examinationType ();

    examinationType (const ::xercesc::DOMElement& e,
                     ::xml_schema::flags f = 0,
                     ::xml_schema::container* c = 0);

    examinationType (const examinationType& x,
                     ::xml_schema::flags f = 0,
                     ::xml_schema::container* c = 0);

    virtual examinationType*
    _clone (::xml_schema::flags f = 0,
            ::xml_schema::container* c = 0) const;

    examinationType&
    operator= (const examinationType& x);

    virtual 
    ~examinationType ();

    // Implementation.
    //
    protected:
    void
    parse (::xsd::cxx::xml::dom::parser< char >&,
           ::xml_schema::flags);

    protected:
    datetime_optional datetime_;
    doctor_optional doctor_;
    link_optional link_;
    examinationresult_optional examinationresult_;
    totallungcapacity_optional totallungcapacity_;
    vitalcapacity_optional vitalcapacity_;
    notes_optional notes_;
  };
}

#include <iosfwd>

namespace streit
{
  ::std::ostream&
  operator<< (::std::ostream&, const examinationType&);
}

#include <iosfwd>

#include <xercesc/sax/InputSource.hpp>
#include <xercesc/dom/DOMDocument.hpp>
#include <xercesc/dom/DOMErrorHandler.hpp>

namespace streit
{
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

#endif // EXAMINATION_TYPE_HXX
