// Copyright (c) 2005-2023 Code Synthesis.
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis gives permission
// to link this program with the Xerces-C++ library (or with modified
// versions of Xerces-C++ that use the same license as Xerces-C++), and
// distribute linked combinations including the two. You must obey the GNU
// General Public License version 2 in all respects for all of the code
// used other than Xerces-C++. If you modify this copy of the program, you
// may extend this exception to your version of the program, but you are
// not obligated to do so. If you do not wish to do so, delete this
// exception statement from your version.
//
// Furthermore, Code Synthesis makes a special exception for the Free/Libre
// and Open Source Software (FLOSS) which is described in the accompanying
// FLOSSE file.
//

#ifndef FLORA_TYPE_HXX
#define FLORA_TYPE_HXX

#include "floraType-fwd.hxx"

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/config.hxx>

#if (LIBXSD_VERSION != 400002000000000L)
#error XSD runtime version mismatch
#endif

#include <xsd/cxx/pre.hxx>

#include <memory>    // ::std::unique_ptr
#include <limits>    // std::numeric_limits
#include <algorithm> // std::binary_search
#include <utility>   // std::move

#include <xsd/cxx/xml/char-utf8.hxx>

#include <xsd/cxx/tree/exceptions.hxx>
#include <xsd/cxx/tree/elements.hxx>
#include <xsd/cxx/tree/containers.hxx>
#include <xsd/cxx/tree/list.hxx>

#include <xsd/cxx/xml/dom/parsing-header.hxx>

#include "singleLifeFormType-fwd.hxx"

#include "notesType-fwd.hxx"

namespace streit
{
  class floraType: public ::xml_schema::type
  {
    public:
    // rhodophyceae
    //
    typedef ::streit::singleLifeFormType rhodophyceae_type;
    typedef ::xsd::cxx::tree::optional< rhodophyceae_type > rhodophyceae_optional;
    typedef ::xsd::cxx::tree::traits< rhodophyceae_type, char > rhodophyceae_traits;

    const rhodophyceae_optional&
    rhodophyceae () const;

    rhodophyceae_optional&
    rhodophyceae ();

    void
    rhodophyceae (const rhodophyceae_type& x);

    void
    rhodophyceae (const rhodophyceae_optional& x);

    void
    rhodophyceae (::std::unique_ptr< rhodophyceae_type > p);

    // phaeophyceae
    //
    typedef ::streit::singleLifeFormType phaeophyceae_type;
    typedef ::xsd::cxx::tree::optional< phaeophyceae_type > phaeophyceae_optional;
    typedef ::xsd::cxx::tree::traits< phaeophyceae_type, char > phaeophyceae_traits;

    const phaeophyceae_optional&
    phaeophyceae () const;

    phaeophyceae_optional&
    phaeophyceae ();

    void
    phaeophyceae (const phaeophyceae_type& x);

    void
    phaeophyceae (const phaeophyceae_optional& x);

    void
    phaeophyceae (::std::unique_ptr< phaeophyceae_type > p);

    // chlorophyceae
    //
    typedef ::streit::singleLifeFormType chlorophyceae_type;
    typedef ::xsd::cxx::tree::optional< chlorophyceae_type > chlorophyceae_optional;
    typedef ::xsd::cxx::tree::traits< chlorophyceae_type, char > chlorophyceae_traits;

    const chlorophyceae_optional&
    chlorophyceae () const;

    chlorophyceae_optional&
    chlorophyceae ();

    void
    chlorophyceae (const chlorophyceae_type& x);

    void
    chlorophyceae (const chlorophyceae_optional& x);

    void
    chlorophyceae (::std::unique_ptr< chlorophyceae_type > p);

    // spermatophyta
    //
    typedef ::streit::singleLifeFormType spermatophyta_type;
    typedef ::xsd::cxx::tree::optional< spermatophyta_type > spermatophyta_optional;
    typedef ::xsd::cxx::tree::traits< spermatophyta_type, char > spermatophyta_traits;

    const spermatophyta_optional&
    spermatophyta () const;

    spermatophyta_optional&
    spermatophyta ();

    void
    spermatophyta (const spermatophyta_type& x);

    void
    spermatophyta (const spermatophyta_optional& x);

    void
    spermatophyta (::std::unique_ptr< spermatophyta_type > p);

    // floravarious
    //
    typedef ::streit::singleLifeFormType floravarious_type;
    typedef ::xsd::cxx::tree::optional< floravarious_type > floravarious_optional;
    typedef ::xsd::cxx::tree::traits< floravarious_type, char > floravarious_traits;

    const floravarious_optional&
    floravarious () const;

    floravarious_optional&
    floravarious ();

    void
    floravarious (const floravarious_type& x);

    void
    floravarious (const floravarious_optional& x);

    void
    floravarious (::std::unique_ptr< floravarious_type > p);

    // notes
    //
    typedef ::streit::notesType notes_type;
    typedef ::xsd::cxx::tree::optional< notes_type > notes_optional;
    typedef ::xsd::cxx::tree::traits< notes_type, char > notes_traits;

    const notes_optional&
    notes () const;

    notes_optional&
    notes ();

    void
    notes (const notes_type& x);

    void
    notes (const notes_optional& x);

    void
    notes (::std::unique_ptr< notes_type > p);

    // Constructors.
    //
    floraType ();

    floraType (const ::xercesc::DOMElement& e,
               ::xml_schema::flags f = 0,
               ::xml_schema::container* c = 0);

    floraType (const floraType& x,
               ::xml_schema::flags f = 0,
               ::xml_schema::container* c = 0);

    virtual floraType*
    _clone (::xml_schema::flags f = 0,
            ::xml_schema::container* c = 0) const;

    floraType&
    operator= (const floraType& x);

    virtual 
    ~floraType ();

    // Implementation.
    //
    protected:
    void
    parse (::xsd::cxx::xml::dom::parser< char >&,
           ::xml_schema::flags);

    protected:
    rhodophyceae_optional rhodophyceae_;
    phaeophyceae_optional phaeophyceae_;
    chlorophyceae_optional chlorophyceae_;
    spermatophyta_optional spermatophyta_;
    floravarious_optional floravarious_;
    notes_optional notes_;
  };
}

#include <iosfwd>

namespace streit
{
  ::std::ostream&
  operator<< (::std::ostream&, const floraType&);
}

#include <iosfwd>

#include <xercesc/sax/InputSource.hpp>
#include <xercesc/dom/DOMDocument.hpp>
#include <xercesc/dom/DOMErrorHandler.hpp>

namespace streit
{
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

#endif // FLORA_TYPE_HXX
