// Copyright (c) 2005-2023 Code Synthesis.
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis gives permission
// to link this program with the Xerces-C++ library (or with modified
// versions of Xerces-C++ that use the same license as Xerces-C++), and
// distribute linked combinations including the two. You must obey the GNU
// General Public License version 2 in all respects for all of the code
// used other than Xerces-C++. If you modify this copy of the program, you
// may extend this exception to your version of the program, but you are
// not obligated to do so. If you do not wish to do so, delete this
// exception statement from your version.
//
// Furthermore, Code Synthesis makes a special exception for the Free/Libre
// and Open Source Software (FLOSS) which is described in the accompanying
// FLOSSE file.
//

#ifndef SURFACEINTERVAL_TYPE_HXX
#define SURFACEINTERVAL_TYPE_HXX

#include "surfaceintervalType-fwd.hxx"

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/config.hxx>

#if (LIBXSD_VERSION != 400002000000000L)
#error XSD runtime version mismatch
#endif

#include <xsd/cxx/pre.hxx>

#include <memory>    // ::std::unique_ptr
#include <limits>    // std::numeric_limits
#include <algorithm> // std::binary_search
#include <utility>   // std::move

#include <xsd/cxx/xml/char-utf8.hxx>

#include <xsd/cxx/tree/exceptions.hxx>
#include <xsd/cxx/tree/elements.hxx>
#include <xsd/cxx/tree/containers.hxx>
#include <xsd/cxx/tree/list.hxx>

#include <xsd/cxx/xml/dom/parsing-header.hxx>

#include "infinity-fwd.hxx"

#include "wayaltitudeType-fwd.hxx"

#include "exposuretoaltitudeType-fwd.hxx"

namespace streit
{
  class surfaceintervalType: public ::xml_schema::type
  {
    public:
    // infinity
    //
    typedef ::streit::infinity infinity_type;
    typedef ::xsd::cxx::tree::optional< infinity_type > infinity_optional;
    typedef ::xsd::cxx::tree::traits< infinity_type, char > infinity_traits;

    const infinity_optional&
    infinity () const;

    infinity_optional&
    infinity ();

    void
    infinity (const infinity_type& x);

    void
    infinity (const infinity_optional& x);

    void
    infinity (::std::unique_ptr< infinity_type > p);

    // passedtime
    //
    typedef ::xml_schema::integer passedtime_type;
    typedef ::xsd::cxx::tree::optional< passedtime_type > passedtime_optional;
    typedef ::xsd::cxx::tree::traits< passedtime_type, char > passedtime_traits;

    const passedtime_optional&
    passedtime () const;

    passedtime_optional&
    passedtime ();

    void
    passedtime (const passedtime_type& x);

    void
    passedtime (const passedtime_optional& x);

    // wayaltitude
    //
    typedef ::streit::wayaltitudeType wayaltitude_type;
    typedef ::xsd::cxx::tree::sequence< wayaltitude_type > wayaltitude_sequence;
    typedef wayaltitude_sequence::iterator wayaltitude_iterator;
    typedef wayaltitude_sequence::const_iterator wayaltitude_const_iterator;
    typedef ::xsd::cxx::tree::traits< wayaltitude_type, char > wayaltitude_traits;

    const wayaltitude_sequence&
    wayaltitude () const;

    wayaltitude_sequence&
    wayaltitude ();

    void
    wayaltitude (const wayaltitude_sequence& s);

    // exposuretoaltitude
    //
    typedef ::streit::exposuretoaltitudeType exposuretoaltitude_type;
    typedef ::xsd::cxx::tree::optional< exposuretoaltitude_type > exposuretoaltitude_optional;
    typedef ::xsd::cxx::tree::traits< exposuretoaltitude_type, char > exposuretoaltitude_traits;

    const exposuretoaltitude_optional&
    exposuretoaltitude () const;

    exposuretoaltitude_optional&
    exposuretoaltitude ();

    void
    exposuretoaltitude (const exposuretoaltitude_type& x);

    void
    exposuretoaltitude (const exposuretoaltitude_optional& x);

    void
    exposuretoaltitude (::std::unique_ptr< exposuretoaltitude_type > p);

    // Constructors.
    //
    surfaceintervalType ();

    surfaceintervalType (const ::xercesc::DOMElement& e,
                         ::xml_schema::flags f = 0,
                         ::xml_schema::container* c = 0);

    surfaceintervalType (const surfaceintervalType& x,
                         ::xml_schema::flags f = 0,
                         ::xml_schema::container* c = 0);

    virtual surfaceintervalType*
    _clone (::xml_schema::flags f = 0,
            ::xml_schema::container* c = 0) const;

    surfaceintervalType&
    operator= (const surfaceintervalType& x);

    virtual 
    ~surfaceintervalType ();

    // Implementation.
    //
    protected:
    void
    parse (::xsd::cxx::xml::dom::parser< char >&,
           ::xml_schema::flags);

    protected:
    infinity_optional infinity_;
    passedtime_optional passedtime_;
    wayaltitude_sequence wayaltitude_;
    exposuretoaltitude_optional exposuretoaltitude_;
  };
}

#include <iosfwd>

namespace streit
{
  ::std::ostream&
  operator<< (::std::ostream&, const surfaceintervalType&);
}

#include <iosfwd>

#include <xercesc/sax/InputSource.hpp>
#include <xercesc/dom/DOMDocument.hpp>
#include <xercesc/dom/DOMErrorHandler.hpp>

namespace streit
{
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

#endif // SURFACEINTERVAL_TYPE_HXX
